language: scala
scala:
  - 2.12.8
jdk:
  - openjdk8
cache:
  directories:
    - "$HOME/.ivy2/cache"
    - "$HOME/.sbt/boot/"
before_cache:
  - find $HOME/.ivy2 -name "ivydata-*.properties" -delete
  - find $HOME/.sbt -name "*.lock" -delete
before_install:
  - git fetch --tags
install:
  - ". $HOME/.nvm/nvm.sh"
  - nvm install stable
  - nvm use stable
  - npm install jsdom
stages:
  - name: test
  - name: release
    if: ((branch = master AND type = push) OR (tag IS present)) AND NOT fork
jobs:
  include:
    # stage="test" if no stage is specified
    - name: compile
      script: sbt facade/test demo/fastOptJS::webpack demo/fastOptJS
    - stage: release
      script: sbt ci-release
